# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waythrough < Formula
  desc "MCP server that connects coding agents to LSP servers"
  homepage "https://github.com/gustavofsantos/waythrough"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gustavofsantos/waythrough/releases/download/v0.1.1/waythrough_0.1.1_darwin_amd64.tar.gz"
      sha256 "b8b00f5dda9f6824d899b191038cf55306d68e90bce828bf62f65432b95ce0f7"

      define_method(:install) do
        bin.install "waythrough"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gustavofsantos/waythrough/releases/download/v0.1.1/waythrough_0.1.1_darwin_arm64.tar.gz"
      sha256 "cf44e450671c1dc838014b2538a9e667d5effc37dad346bb978ae8a0dbc4202f"

      define_method(:install) do
        bin.install "waythrough"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gustavofsantos/waythrough/releases/download/v0.1.1/waythrough_0.1.1_linux_amd64.tar.gz"
      sha256 "eecd701511b9d934fa33b914a13b36408e6280d0280903f437d69b91b88f4f8e"
      define_method(:install) do
        bin.install "waythrough"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gustavofsantos/waythrough/releases/download/v0.1.1/waythrough_0.1.1_linux_arm64.tar.gz"
      sha256 "68983e17fdc4a4fa000d54427a0f753b2ae21587181d15d70168eddcf1ee3f56"
      define_method(:install) do
        bin.install "waythrough"
      end
    end
  end

  test do
    assert_match "waythrough version #{version}", shell_output("#{bin}/waythrough --version")
  end
end
